name: Publish to PowerShell Gallery

on: [workflow_dispatch]

jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        
        - name: Publish
          env:
            NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          run: .\Extra\Publish.ps1
          shell: pwsh