name: Pester

on: [workflow_dispatch]

jobs:
  run-psscriptanalyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Invoke-Pester -EnableExit
        env:
          IDNW_BASE_URL: ${{ secrets.IDNW_BASE_URL }}
          IDNW_CLIENT_ID: ${{ secrets.IDNW_CLIENT_ID }}
          IDNW_CLIENT_SECRET: ${{ secrets.IDNW_CLIENT_SECRET }}
        working-directory: ./Tests/
